version: '3.7'

services:
  what_to_do_app:
    build: .
    container_name: what_to_do_app
    networks:
      - what_to_do_app_network
    restart: unless-stopped
    env_file: .env
    command: /bin/bash -c " \
      uvicorn app.main:app --forwarded-allow-ips '*' --proxy-headers --host 0.0.0.0 --port 5000 --reload"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - what_to_do_app_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - what_to_do_app
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 256M

  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      - what_to_do_app_network
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${DEVELOPER_EMAIL} -d ${DOMAIN_NAME} --agree-tos

networks:
  what_to_do_app_network:
    name: what_to_do_app_network
    driver: bridge