version: '3.7'

services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - what_to_do_app_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - what_to_do_app

  what_to_do_app:
    build: .
    container_name: what_to_do_app
    networks:
      - what_to_do_app_network
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/apps/what_to_do_app
    env_file: .env
    command: /bin/bash -c " \
      uvicorn app.main:app --forwarded-allow-ips '*' --proxy-headers --host 0.0.0.0 --port 5000 --reload"

networks:
  what_to_do_app_network:
    name: what_to_do_app_network
    driver: bridge